name: Build Cheat DLL

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      run: |
        msbuild ACinternal.sln /p:Configuration=Release /p:Platform=x86

    - name: Upload DLL Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AssaultCubeMod
        path: |
          Release/*.dll
          bin/Release/*.dll
